version: '3.8'

services:
  pgdb:
    image: postgres:14.2
    container_name: pgdb
    ports:
      - host_ip: 127.0.0.1
        published: 5432
        target: 5432
    volumes:
      - type: volume
        source: pgdb-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=Pas5w0rd*
      - POSTGRES_DB=Wish

volumes:
  pgdb-data:
